[package]
name = "paradise"
version = "0.1.0"
authors = ["mako <marcus.yass@gmail.com>"]

[dependencies]
sled = "0.15.17"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.28"
byteorder = "1.2.6"


